FROM java:8-jre
WORKDIR usr/src
ENV MYSQL_DATABASE=favouriteservicedb
ENV MYSQL_USER=root
ENV MYSQL_PASSWORD=0987
ENV MYSQL_CI_URL=jdbc:mysql://localhost:3306/favouriteservicedb?createDatabaseIfNotExist=true&user=root&password=0987&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
ADD ./target/favservice-0.0.1-SNAPSHOT.jar /usr/src/favservice-0.0.1-SNAPSHOT.jar 
ENTRYPOINT ["java", "-jar","favservice-0.0.1-SNAPSHOT.jar"]
